name: Deploy to GitHub Pages

on:
  push:
    branches: master
    # use ubuntu-latest image to run steps on
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v2
    
      
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
      
    - name: Publish .NET Core Project
      run: dotnet publish BlazorApp/BlazorApp.csproj -c Release --output release --nologo
      
    - name: Change base-tag in index.html from / to BlazorApp
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorApp\/" \/>/g' release/wwwroot/index.html

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: release/wwwroot 
